// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFMYvohYPOpoa-JEc-_G0Sar3a8yfHZ04',
    appId: '1:648872152404:web:1108db317e3d411c364cc1',
    messagingSenderId: '648872152404',
    projectId: 'quizapp-a2a35',
    authDomain: 'quizapp-a2a35.firebaseapp.com',
    storageBucket: 'quizapp-a2a35.appspot.com',
    measurementId: 'G-ZNC7LG8MBE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACYLWIRgFB8SLWLpsvgHAqy8Z1sMWwcRU',
    appId: '1:648872152404:android:a8cf41deeab8ed99364cc1',
    messagingSenderId: '648872152404',
    projectId: 'quizapp-a2a35',
    storageBucket: 'quizapp-a2a35.appspot.com',
  );
}
